version: "3.2"
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6379:6379"
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "npm run migration:up && npm run start:prod"
    env_file:
      - ./.env
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'